version: '3.9'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1024M
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf

  # core_server:
  #   build:
  #     context: .
  #     dockerfile: apps/core_server/Dockerfile
  #   container_name: core_server
  #   restart: unless-stopped
  #   depends_on:
  #     - neo4j
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=production
  #     - NEO4J_URI=bolt://neo4j:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=password
  #   volumes:
  #     - ./apps/core_server:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: ["npm", "run", "start:prod"]

  # client:
  #   build:
  #     context: .
  #     dockerfile: apps/client/Dockerfile
  #   container_name: client
  #   restart: unless-stopped
  #   depends_on:
  #     - core_server
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - NEXT_PUBLIC_API_URL=http://core_server:3001
  #   volumes:
  #     - ./apps/client:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: ["npm", "run", "start"]

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:

networks:
  default:
    driver: bridge
